name: Close Late Pull Requests
on:
  pull_request:
    types: [opened]

jobs:
  close_late_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is late
        id: check_date
        run: |
          DUE_DATE="2025-09-15T23:59:59Z"
          PR_DATE=$(date -d '${{ github.event.pull_request.created_at }}' -u +"%Y-%m-%dT%H:%M:%SZ")
          
          echo "Due date: ${DUE_DATE}"
          echo "PR created: ${PR_DATE}"
          
          if [[ "${PR_DATE}" > "${DUE_DATE}" ]]; then
            echo "is_late=true" >> $GITHUB_OUTPUT
            echo "PR is late!"
          else
            echo "is_late=false" >> $GITHUB_OUTPUT
            echo "PR is on time."
          fi

      - name: Close late PR
        if: steps.check_date.outputs.is_late == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const prNumber = context.payload.pull_request.number;
              const prTitle = context.payload.pull_request.title;
              const prAuthor = context.payload.pull_request.user.login;
              
              // Add comment explaining why PR was closed
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: `⚠️ **Submission Deadline Exceeded**
                
This pull request was submitted after the due date (**September 16, 2025 at 23:59:59 UTC**) and has been automatically closed.

**Submission Details:**
- PR Title: ${prTitle}
- Author: @${prAuthor}
- Submitted: ${{ github.event.pull_request.created_at }}
- Due Date: September 16, 2025 23:59:59 UTC

If you believe this was closed in error or have any questions, please contact the instructor.`
              });
              
              // Close the pull request
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
                state: 'closed'
              });
              
              console.log(`✅ PR #${prNumber} by ${prAuthor} was closed due to late submission.`);
              
            } catch (error) {
              core.setFailed(`❌ Failed to close late PR: ${error.message}`);
              throw error;
            }
